language: php

php:
 - "5.3.3"
 - "5.3"
 - "5.4"

before_install:
 - composer self-update
 - composer install --dev

before_script:
 - mysql -e 'create database `app-db-tests`;'
 - cd tests

script:
 - phpunit
 - php ./coverage-checker.php ./clover.xml 100